#!/bin/bash
# scripts/generate-update-public-key.sh <data-file> <output-swift-file>
#
# Writes Sources/FreeTalker/Update/UpdatePublicKey.swift from keys/release-public-key.base64.
# Invoked automatically, on every `swift build`/`swift test`, by the GenerateUpdatePublicKey
# SwiftPM build tool plugin (Plugins/GenerateUpdatePublicKey/Plugin.swift) — never run by hand,
# and never by scripts/release.sh or scripts/make-release-signing-key.sh (both read
# keys/release-public-key.base64 directly; this script is the only thing that ever turns it into
# Swift source).
#
# This is what makes "the compiled constant cannot drift from the data file" true BY
# CONSTRUCTION rather than by a compare-and-fail check: UpdatePublicKey.swift is regenerated from
# keys/release-public-key.base64 on every build (it is gitignored and never hand-edited — see
# .gitignore), so there is nothing else for it to disagree with. What can still go wrong is
# keys/release-public-key.base64 itself being malformed (missing, empty, multi-line, not valid
# base64 of exactly 32 raw bytes) — read_established_public_key_base64
# (scripts/lib/public-key-data-file.sh) catches every one of those and this script fails loudly,
# which fails the whole build loudly, rather than silently compiling in a guessed or empty value.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/public-key-data-file.sh
source "$SCRIPT_DIR/lib/public-key-data-file.sh"

if [[ $# -ne 2 ]]; then
    echo "usage: $0 <data-file> <output-swift-file>" >&2
    exit 1
fi
DATA_FILE="$1"
OUTPUT_FILE="$2"

if ! PUBLIC_KEY_BASE64="$(read_established_public_key_base64 "$DATA_FILE")"; then
    echo "error: could not generate $OUTPUT_FILE — see the error above." >&2
    exit 1
fi
if [[ -z "$PUBLIC_KEY_BASE64" ]]; then
    echo "error: $DATA_FILE does not exist. The release-signing public key must be committed" >&2
    echo "before FreeTalker can build. Run scripts/make-release-signing-key.sh once (see" >&2
    echo "README.md) to generate it, or restore $DATA_FILE from git." >&2
    exit 1
fi

cat >"$OUTPUT_FILE" <<EOF
import CryptoKit
import Foundation

/// The public half of the Ed25519 release-signing keypair (see
/// scripts/make-release-signing-key.sh). Compiled into every build — this is the trust anchor
/// \`UpdateSignatureVerifier\` checks a downloaded release's signature against. It is independent
/// of any machine-local keychain trust. The matching private key never leaves the release
/// signer's machine; regenerating this file with a new keypair is a breaking change for every
/// already-built app, since it can only ever trust the ONE public key it was compiled with.
///
/// GENERATED by scripts/generate-update-public-key.sh from keys/release-public-key.base64 on
/// every build (see Plugins/GenerateUpdatePublicKey) — do not hand-edit; edit
/// keys/release-public-key.base64 instead, then rebuild.
enum UpdatePublicKey {
    static let base64 = "$PUBLIC_KEY_BASE64"

    static var current: Curve25519.Signing.PublicKey? { Self.parse(base64: base64) }

    /// Pulled out of \`current\` so tests can exercise the exact parsing/validation logic
    /// (length check, \`CryptoKit\` construction) against both this real compiled-in key and
    /// deliberately invalid inputs, without needing a second compiled-in constant.
    static func parse(base64: String) -> Curve25519.Signing.PublicKey? {
        guard let raw = Data(base64Encoded: base64), raw.count == 32,
            let key = try? Curve25519.Signing.PublicKey(rawRepresentation: raw)
        else { return nil }
        return key
    }
}
EOF
