#!/bin/bash
# scripts/make-release-signing-key.sh — one-time setup for the Ed25519 release-signing keypair.
#
# scripts/release.sh signs every release artifact with the PRIVATE half of this keypair;
# SelfUpdater verifies that signature against the PUBLIC half, which is compiled into the app
# (Sources/FreeTalker/Update/UpdatePublicKey.swift, generated by this script). This is the
# actual trust boundary for self-update — unlike codesign trust-chain validation (which fails
# closed with CSSMERR_TP_NOT_TRUSTED on every machine except the one where a human manually
# marked the self-signed cert "Always Trust" in Keychain Access), it never depends on any
# machine's local keychain trust, so it verifies identically everywhere the app runs.
#
# Run this ONCE, manually, and only ever on the machine that publishes releases:
#   scripts/make-release-signing-key.sh
#
# The PRIVATE key is written OUTSIDE this repository (default: ~/.freetalker/) and must never
# be committed — losing it means no future release can ever be verified as authentic by an app
# that already has the current public key compiled in; there is no recovery path other than
# generating a new keypair and shipping a build with the new public key, which every existing
# install must then separately be told to trust again. Back the private key up somewhere safe
# (a password manager or an encrypted volume) as soon as this script finishes.

set -euo pipefail

KEY_DIR="${FREETALKER_RELEASE_SIGNING_KEY_DIR:-$HOME/.freetalker}"
PRIVATE_KEY_PATH="${FREETALKER_RELEASE_SIGNING_KEY:-$KEY_DIR/release-signing-key.pem}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC_KEY_SWIFT="$REPO_ROOT/Sources/FreeTalker/Update/UpdatePublicKey.swift"

if [[ -f "$PRIVATE_KEY_PATH" ]]; then
    echo "A release signing key already exists at $PRIVATE_KEY_PATH. Nothing to do."
    echo "Delete it manually first if you really want to generate a new one — doing so makes"
    echo "every already-built app (which has the OLD public key compiled in) unable to verify"
    echo "any release signed with the new key, until it's rebuilt with the new one."
    exit 0
fi

PRIVATE_KEY_DIR="$(dirname "$PRIVATE_KEY_PATH")"
mkdir -p "$PRIVATE_KEY_DIR"
chmod 700 "$PRIVATE_KEY_DIR"

echo "Generating Ed25519 release-signing keypair..."
openssl genpkey -algorithm ED25519 -out "$PRIVATE_KEY_PATH"
chmod 600 "$PRIVATE_KEY_PATH"

PUBLIC_KEY_PEM="$(mktemp)"
PUBLIC_KEY_DER="$(mktemp)"
trap 'rm -f "$PUBLIC_KEY_PEM" "$PUBLIC_KEY_DER"' EXIT

openssl pkey -in "$PRIVATE_KEY_PATH" -pubout -out "$PUBLIC_KEY_PEM"
openssl pkey -pubin -in "$PUBLIC_KEY_PEM" -outform DER -out "$PUBLIC_KEY_DER"

# An Ed25519 SubjectPublicKeyInfo DER encoding is always exactly 44 bytes: a fixed 12-byte
# algorithm-identifier header (30 2a 30 05 06 03 2b 65 70 03 21 00) followed by the raw 32-byte
# public key — the last 32 bytes are exactly what CryptoKit's
# Curve25519.Signing.PublicKey(rawRepresentation:) expects. Empirically confirmed against this
# machine's openssl (3.6.2).
DER_SIZE="$(wc -c <"$PUBLIC_KEY_DER" | tr -d ' ')"
if [[ "$DER_SIZE" -ne 44 ]]; then
    echo "error: unexpected Ed25519 public key DER size ($DER_SIZE bytes, expected 44) — refusing" >&2
    echo "to write a public key that might not be the raw 32-byte key CryptoKit expects." >&2
    exit 1
fi
PUBLIC_KEY_BASE64="$(tail -c 32 "$PUBLIC_KEY_DER" | openssl base64 -A)"

cat >"$PUBLIC_KEY_SWIFT" <<EOF
import CryptoKit
import Foundation

/// The public half of the Ed25519 release-signing keypair (see
/// scripts/make-release-signing-key.sh). Compiled into every build — this is the trust anchor
/// \`UpdateSignatureVerifier\` checks a downloaded release's signature against. It is independent
/// of any machine-local keychain trust. The matching private key never leaves the release
/// signer's machine; regenerating this file with a new keypair is a breaking change for every
/// already-built app, since it can only ever trust the ONE public key it was compiled with.
enum UpdatePublicKey {
    static let base64 = "$PUBLIC_KEY_BASE64"

    static var current: Curve25519.Signing.PublicKey? { Self.parse(base64: base64) }

    /// Pulled out of \`current\` so tests can exercise the exact parsing/validation logic
    /// (length check, \`CryptoKit\` construction) against both this real compiled-in key and
    /// deliberately invalid inputs, without needing a second compiled-in constant.
    static func parse(base64: String) -> Curve25519.Signing.PublicKey? {
        guard let raw = Data(base64Encoded: base64), raw.count == 32,
            let key = try? Curve25519.Signing.PublicKey(rawRepresentation: raw)
        else { return nil }
        return key
    }
}
EOF

echo
echo "Private key written to: $PRIVATE_KEY_PATH (outside this repo, mode 600)."
echo "Public key compiled into: $PUBLIC_KEY_SWIFT — commit this file."
echo
echo "IMPORTANT: back up $PRIVATE_KEY_PATH somewhere safe right now. If it's lost, no future"
echo "release can ever be verified by an app already built with this public key."
echo
echo "scripts/release.sh reads the private key from \$FREETALKER_RELEASE_SIGNING_KEY (default:"
echo "$PRIVATE_KEY_PATH)."
